dropmap/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('', include('places.urls')),
    path('', include('about.urls')),
    path('', include('shop.urls')),
    path('', include('user.urls')),
    path('api/places/', include('places.api.urls')),
    path('api/shop/', include('shop.api.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

places/api/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    PlaceListAPIView,
    CityViewSet, PlaceSingleAPIView)

app_name = 'places-api'
urlpatterns = [
    # path('', TemplateView.as_view(template_name="home/index.html")),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),

    # path('get_by_city/<model>/<slug:city_slug>', PlaceListAPIView.as_view(), name='places_api_on_map'),
    # todo get by second / stock name
    path('get_by_city/<model>/<slug:city_slug>', PlaceListAPIView.as_view(), name='places_api_on_map'),
    path('get/<model>/<id>', PlaceSingleAPIView.as_view({'get': 'retrieve'}), name='places_api_on_map'),
    path('get_cities/<slug:city_slug>', CityViewSet.as_view({'get': 'retrieve'}), name='place_api_get_city'),
    path('get_cities', CityViewSet.as_view({'get': 'list'}), name='place_api_get_cities'),
]

places/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'places'
urlpatterns = [
    path('mapseconds/', views.MapSecondsView.as_view(), name='place_map_seconds'),
    path('mapstocks/', views.MapStockView.as_view(), name='place_map_stocks'),
    path('places/second/<int:pk>/', views.SecondDetailView.as_view(), name='second_detail'),
    path('places/stock/<int:pk>/', views.StockDetailView.as_view(), name='stock_detail'),
    # todo change with nothing
    path('places/', views.SecondListView.as_view(), name='place_all'),
    path('places/second/', views.SecondListView.as_view(), name='all_seconds'),
    path('places/stock', views.StockListView.as_view(), name='all_stocks'),
    path('places/suggest/', views.SuggestPlacetView.as_view(), name='place_suggest'),
    ]

places/models.py
from sorl.thumbnail import get_thumbnail
from unidecode import unidecode
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from geoposition.fields import GeopositionField
from django.templatetags.static import static

# todo set desc
NO_DESC_TEXT_MAP = "Інфи нема. Будеш там, дай знати, яка там сітуейшн\nInstagram: <a href='https://www.instagram.com/dropmap' target='_blank'>@dropmap</a>"
# NO_DESC_TEXT_MAP = None

PLACE_TYPES = (
    ("SC", "Секонд"),
    ("ST", "Сток"),
)
DAYS = (
    ("everyday", "Кожен день"),
    ("monday", "Понеділок"),
    ("tuesday", "Вівторок"),
    ("wednesday", "Середа"),
    ("thursday", "Четверг"),
    ("friday", "П'ятниця"),
    ("saturday", "Субота"),
    ("sunday", "Неділя"),
)
User = settings.AUTH_USER_MODEL


def upload_location(instance, filename):
    if instance._meta.object_name == "Stock":
        return "stocks/%s/%s" % (slugify(instance.name, allow_unicode=True), filename)
    if instance._meta.object_name == "Second":
        return "seconds/%s/%s" % (slugify(instance.name, allow_unicode=True), filename)


# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=30, unique=True)
    slug = models.CharField(max_length=30, blank=True)
    longitude = models.FloatField()
    latitude = models.FloatField()
    boundaries = models.FloatField()

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.name))
        super(City, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Second(models.Model):
    city = models.ForeignKey(City, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    coordinates = GeopositionField()
    # to get coor obj.coordinates.latitude & longitude
    day = models.CharField(max_length=10, choices=DAYS, default=DAYS[0], verbose_name="День оновлення")
    address = models.CharField(max_length=60)
    rating = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(5)])
    description = models.TextField(max_length=256, blank=True, null=True)

    # details
    phone = models.CharField(max_length=13, blank=True, null=True, help_text="Вводь телефон у форматі 099 000 00 00")
    shop_site = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    # main image original & cropping
    main_image = ProcessedImageField(upload_to=upload_location, blank=True, null=True,
                                     format='JPEG',
                                     options={'quality': 80}, verbose_name="Головне фото", help_text="Зазвичай входу")
    # list_page_cropping = ImageSpecField(source='main_image',
    #                                     processors=[ResizeToFill(230, 200)],
    #                                     format='JPEG',
    #                                     options={'quality': 80})
    # detail_page_cropping = ImageSpecField(source='main_image',
    #                                       processors=[ResizeToFill(350, 250)],
    #                                       format='JPEG',
    #                                       options={'quality': 80})
    # map_cropping = ImageSpecField(source='main_image',
    #                               processors=[ResizeToFill(50, 50)],
    #                               format='JPEG',
    #                               options={'quality': 50})

    # additional images
    image2 = ProcessedImageField(upload_to=upload_location,
                                 processors=[ResizeToFill(350, 250)],
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)
    image3 = ProcessedImageField(upload_to=upload_location,
                                 processors=[ResizeToFill(350, 250)],
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)

    show_on_map = models.BooleanField(default=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse('places:place_detail', kwargs={'slug': self.slug})
        return reverse('places:second_detail', kwargs={'pk': self.id})

    # getters for serializer
    def get_name(self):
        return self.name

    def get_day(self):
        return self.day

    def get_sale(self):
        return None

    def get_address(self):
        return self.address

    def get_map_photo_url(self):
        # todo set default image
        if self.main_image:
            image = get_thumbnail(self.main_image, '50x50', crop='center', quality=90)
            return image.url
        else:
            # todo or return nothing
            image = static('img/no-image50x50.jpg')
            return image

    def get_coordinates(self):
        return [self.coordinates.longitude, self.coordinates.latitude]

    def get_description(self):
        return self.description if self.description else NO_DESC_TEXT_MAP


class Stock(models.Model):
    city = models.ForeignKey(City, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    coordinates = GeopositionField()
    # to get coor obj.coordinates.latitude & longitude

    address = models.CharField(max_length=60)
    rating = models.PositiveSmallIntegerField(default=0, validators=[MaxValueValidator(5)])
    sale = models.CharField(max_length=60, blank=True, null=True)

    description = models.TextField(max_length=256, blank=True, null=True)

    # details
    phone = models.CharField(max_length=13, blank=True, null=True)
    shop_site = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    # main image original & cropping
    main_image = ProcessedImageField(upload_to=upload_location, blank=True, null=True,
                                     format='JPEG',
                                     options={'quality': 80}, verbose_name="Головне фото", help_text="Зазвичай входу")

    # additional images
    image2 = ProcessedImageField(upload_to=upload_location,
                                 processors=[ResizeToFill(350, 250)],
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)
    image3 = ProcessedImageField(upload_to=upload_location,
                                 processors=[ResizeToFill(350, 250)],
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)

    show_on_map = models.BooleanField(default=True)
    owner = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('places:stock_detail', kwargs={'pk': self.id})

    # getters for serializer
    def get_name(self):
        return self.name

    def get_day(self):
        return None

    def get_sale(self):
        return self.sale if self.sale else ""

    def get_address(self):
        return self.address

    def get_detail_photo_url(self):
        # todo set default image
        return self.detail_page_cropping.url if self.main_image else static('img/no-image.png')

    def get_map_photo_url(self):
        if self.main_image:
            image = get_thumbnail(self.main_image, '50x50', crop='center', quality=90)
            return image.url
        else:
            image = static('img/no-image50x50.jpg')
            return image

    def get_list_photo_url(self):
        # todo set default image
        return self.list_page_cropping.url if self.main_image else static('img/no-image50x50.jpg')

    def get_coordinates(self):
        return [self.coordinates.longitude, self.coordinates.latitude]

    def get_description(self):
        return self.description if self.description else NO_DESC_TEXT_MAP


class SuggetionPlace(models.Model):
    type = models.CharField(max_length=2, choices=PLACE_TYPES, default=PLACE_TYPES[0])
    city = models.ForeignKey(City, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    coordinates = GeopositionField()
    description = models.CharField(max_length=256, blank=True, null=True)
    checked = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    city = models.OneToOneField(Second, on_delete=models.CASCADE, primary_key=True)
    mon = models.PositiveSmallIntegerField(blank=True, null=True)
    tue = models.PositiveSmallIntegerField(blank=True, null=True)
    wed = models.PositiveSmallIntegerField(blank=True, null=True)
    thu = models.PositiveSmallIntegerField(blank=True, null=True)
    fri = models.PositiveSmallIntegerField(blank=True, null=True)
    sat = models.PositiveSmallIntegerField(blank=True, null=True)
    sun = models.PositiveSmallIntegerField(blank=True, null=True)

places/forms.py
from django import forms
from .models import Second

class SecondForm(forms.ModelForm):
    class Meta:
        model = Second
        fields =('name', )

places/api/views.py
from django.http import Http404
from rest_framework import permissions, viewsets
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView, RetrieveAPIView, get_object_or_404
from rest_framework.response import Response

from places.models import Second, City, Stock
from .serializers import PlaceSerializer, CitySerializer


class PlaceListAPIView(ListAPIView):
    serializer_class = PlaceSerializer

    def get_queryset(self):
        """
        This view should return a list of all models by
        the city passed in the URL
        """

        city_slug = self.kwargs['city_slug']
        if self.kwargs['model'] == "second":
            list = Second.objects.filter(city__slug=city_slug).filter(show_on_map=True)
        else:
            list = Stock.objects.filter(city__slug=city_slug).filter(show_on_map=True)

        if list:
            return list
        else:
            raise Http404


class PlaceSingleAPIView(viewsets.ViewSet):
    def retrieve(self, request, model=None, id=None):
        if model == "second":
            place = get_object_or_404(Second, id=id)
        else:
            place = get_object_or_404(Stock, id=id)
        serializer = PlaceSerializer(place)
        return Response(serializer.data)


class CityViewSet(viewsets.ViewSet):
    """
    A ViewSet for listing or retrieving cities.
    """

    def list(self, request):
        queryset = City.objects.all()
        serializer = CitySerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, city_slug=None):
        city = get_object_or_404(City, slug=city_slug)
        serializer = CitySerializer(city)
        return Response(serializer.data)

places/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from django.views.generic import CreateView
from django.core.paginator import Paginator

from places.models import Second, SuggetionPlace, Stock, Schedule


class MapSecondsView(generic.TemplateView):
    template_name = 'places/map_seconds.html'

class MapStockView(generic.TemplateView):
    template_name = 'places/map_stocks.html'

# todo separate templates for detail view ? design ?
class SecondDetailView(generic.DetailView):
    model = Second
    context_object_name = 'place'
    template_name = 'places/detail_place.html'

    def get_context_data(self, **kwargs):
        context = super(SecondDetailView, self).get_context_data(**kwargs)
        context['type'] = "секонд"
        context['additional_info'] = self.object.phone or self.object.phone
        context['second_list'] = Second.objects.order_by('-rating', '?')[:4]
        try:
            context['shedule'] = Schedule.objects.get(city = self.object.id)
        except ObjectDoesNotExist:
            pass
        return context


class StockDetailView(generic.DetailView):
    model = Stock
    context_object_name = 'place'
    template_name = 'places/detail_place.html'

    def get_context_data(self, **kwargs):
        context = super(StockDetailView, self).get_context_data(**kwargs)
        context['type'] = "сток"
        context['second_list'] = Stock.objects.order_by('-rating', '?')[:4]

        return context


class SecondListView(generic.ListView):
    # model = Second
    template_name = 'places/place_list.html'
    context_object_name = 'second_list'
    paginate_by = 12
    # paginate_by = 2
    queryset = Second.objects.all().filter(show_on_map=True).order_by('-rating')  # Default: Model.objects.all()

    def get_context_data(self, **kwargs):
        context = super(SecondListView, self).get_context_data(**kwargs)
        context['type'] = "second"
        return context

class StockListView(generic.ListView):
    template_name = 'places/place_list.html'
    context_object_name = 'second_list'
    paginate_by = 12
    # paginate_by = 2
    queryset = Stock.objects.all().filter(show_on_map=True).order_by('-rating')  # Default: Model.objects.all()

    def get_context_data(self, **kwargs):
        context = super(StockListView, self).get_context_data(**kwargs)
        context['type'] = "stock"
        return context


class SuggestPlacetView(CreateView):
    template_name = "places/place_suggest.html"
    model = SuggetionPlace
    success_url = "/"
    fields = ['type', 'city', 'name', 'coordinates', 'description']

places/templates/places/detail_place.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="place-item-detail"{% endblock %}

{% block title %}{{ place.name }} на {{ place.address }} - Dropmap{% endblock %}

{% block menu-active-item %}УСІ {{ type|upper }}И{% endblock %}

{% block all-places-active %}menu__item--active{% endblock %}

{% block viewport %}
    <meta name="viewport" content="width=device-width,initial-scale=1">{% endblock %}

{% block description %}
    <meta name="description" content="Вся інфа про {{ type }} {{ place.name }} на {{ place.address }} у м. Львів.{% if shedule %} Навіть про розклад цін на тиждень.{% endif %} Drop map.">
{% endblock %}

{% block keywords %}
    <meta name="keywords" content="{{ place.name }}, {{ type }}, львів">
{% endblock %}

{# END PAGE SETTINGS #}
{% block stylesheet %}
    {# todo set in prod#}
    {#    <link rel="stylesheet" href="{% static 'styles/includes/leaflet.css' %}"> #}
    {# todo download it and store localy #}
    <link rel="stylesheet" href="https://elmarquis.github.io/Leaflet.GestureHandling/dist/leaflet-gesture-handling.css"
          type="text/css">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
{% endblock %}
{% block content %}
    {#    todo fix it + glide#}
    <div class="breadcrumb">
        <ul class="breadcrumb__list">
            <li class="breadcrumb__item">
                <!-- if breadcrumb is single--><a href="#" title="DROPMAP.COM.UA" class="breadcrumb__link">DROPMAP.COM.UA</a>
            </li>
            <li class="breadcrumb__item">
                <!-- if breadcrumb is single--><a href="
                    {% if type == "сток" %}{% url "places:all_stocks" %}{% else %}{% url "places:all_seconds" %}{% endif %}"
                                                  title="УСІ {{ type|upper }}И"
                                                  class="breadcrumb__link">УСІ {{ type|upper }}И</a>
            </li>
            <li class="breadcrumb__item"><span class="breadcrumb__link-current">EUROSHOP</span></li>
        </ul>
    </div>


    <div class="container">
        <div class="row">
            <div id="intro" class="col-lg-7">
                <div id="glideslider" class="glide">
                    <div data-glide-el="track" class="glide__track">
                        <ul class="glide__slides">
                            {% thumbnail place.main_image "350x250" crop="center" as im %}
                                <li style="background-image: url('{{ im.url }}');"
                                    class="glide__slide"></li>
                            {% empty %}
                                <li style="background-image: url('{% static 'img/no-image.png' %}');"
                                    class="glide__slide"></li>
                            {% endthumbnail %}
                            {% thumbnail place.image2 "350x250" crop="center" as im %}
                                <li style="background-image: url('{{ im.url }}');"
                                    class="glide__slide"></li>
                            {% endthumbnail %}
                            {% thumbnail place.image3 "350x250" crop="center" as im %}
                                <li style="background-image: url('{{ im.url }}');"
                                    class="glide__slide"></li>
                            {% endthumbnail %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="m-place-description col-lg-5">
                <h1>{{ place.name }}</h1>
                {% if place.description %}
                    <div class="info-holder">
                        <h4 class="bold">Про магазин</h4>
                        <h5 class="info-holder--info">{{ place.description }}</h5>
                    </div>
                {% endif %}
                <div class="info-holder">
                    <h4 class="bold">Адреса</h4>
                    <h5>{{ place.address }}</h5>
                </div>
                <div class="info-holder">
                    <h4 class="bold">Рейтинг</h4>
                    <div class="icon-holder">
                        <svg class="icon small15">
                            <use xlink:href="{% static "img/sprite.svg" %}#icon-star_24px"></use>
                        </svg>
                        <h5>{{ place.rating }}</h5>
                    </div>
                </div>
                <div class="info-holder">
                    <h4 class="bold">Місто</h4>
                    <h5>{{ place.city }}</h5>
                </div>
                {% if place.day %}
                    <div class="info-holder">
                        <h4 class="bold">День оновлення</h4>
                        <h5>{{ place.get_day_display }}</h5>
                    </div>
                {% endif %}
                {% if place.sale %}
                    <div class="info-holder">
                        <h4 class="bold">Акції</h4>
                        <h5>{{ place.sale }}</h5>
                    </div>
                {% endif %}
                {% if additional_info %}
                    <h5 class="bold margin10px">Тут навіть є:</h5>
                    {% if place.shop_site %}
                        <div class="info-holder">
                            <h4>Сайт магазина</h4><a href="facebook.com" target="_blank" rel="noopener noreferrer">facebook.com/dropmap</a>
                        </div>
                    {% endif %}
                    {% if place.phone %}
                        <div class="info-holder">
                            <h4>Контакти</h4><a href="tel:+38{{ place.phone }}">{{ place.phone }}</a>
                        </div>
                    {% endif %}
                    {% if shedule %}
                        <div class="info-holder info-holder-daily">
                            <h4>Тижневий розклад</h4>
                            <div class="icon-holder">
                                <h5>Детальніше</h5>
                                <svg class="icon small">
                                    <use xlink:href="{% static "img/sprite.svg" %}#icon-arrow"></use>
                                </svg>
                            </div>

                            <div class="info-holder--more_info">
                                <div class="holder">
                                    <p>Понеділок</p>
                                    <p>{{ shedule.mon }} грн/кг</p>
                                    <p>Вівторок</p>
                                    <p>{{ shedule.tue }} грн/кг</p>
                                    <p>Середа</p>
                                    <p>{{ shedule.wed }} грн/кг</p>
                                    <p>Четверг</p>
                                    <p>{{ shedule.thu }} грн/кг</p>
                                    <p>П'ятниця</p>
                                    <p>{{ shedule.fri }} грн/кг</p>
                                    <p>Субота</p>
                                    <p>{{ shedule.sat }} грн/кг</p>
                                    {% if shedule.sun %}
                                        <p>Неділя</p>
                                        <p>{{ shedule.sun }} грн/кг</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
                <div class="info-holder info-holder-buttons">
                    <a target="_blank" rel="noopener noreferrer"
                       href="https://www.google.com/maps/search/?api=1&amp;query={{ place.coordinates.latitude }},{{ place.coordinates.longitude }}"
                       class="button-text-icon small-text">
                        <div class="text">Відкрити в Google maps</div>
                        <div class="button-text-icon--holder">
                            <svg class="icon rightTag icon-white small">
                                <use xlink:href="{% static "img/sprite.svg" %}#icon-arrow"></use>
                            </svg>
                        </div>
                    </a>

                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div id="leafletmap-single"></div>
    </div>

    <section class="o-place-offer">
        <div class="container">
            <div class="m-place-offer-line">
                <div class="m-place-offer-line--heading">
                    <h3>Найгодніші {{ type }}и</h3>
                </div>
                <div class="m-place-offer-line--helptext">
                    <p>У Львові</p>
                </div>
            </div>
            <div class="m-place-offer-block">
                <div class="m-place-offer-block--helptext">
                    <p>У Львові</p>
                </div>
                <div class="m-place-offer-block--holder">
                    {% for second in second_list %}
                        <div class="m-place-item">
                        {% thumbnail second.main_image "230x200" crop="center" as im %}
                            <div style="background-image: url('{{ im.url }}');"
                                 class="m-place-item--image">
                        {% empty %}
                            <div style="background-image: url('{% static 'img/no-image.png' %}');"
                                 class="m-place-item--image">
                        {% endthumbnail %}
                    <p>{{ second.description|truncatechars:63 }}</p>
                    </div>
                    <hr>
                    <div class="m-place-item--text-block">
                        <h4>{{ second.name }}</h4>
                        <div class="m-place-item--text-block__info">
                            <svg class="icon icon-text-block">
                                <use xlink:href="{% static 'img/sprite.svg' %}#icon-clock"></use>
                            </svg>
                            <p>{% if second.get_day_display %}{{ second.get_day_display }}{% elif second.sale %}
                                {{ second.sale|truncatechars:20 }}{% else %}Акцій зараз немає{% endif %}</p>
                        </div>
                        <div class="m-place-item--text-block__info">
                            <p>{{ second.rating }}</p>
                            <svg class="icon icon-text-block star">
                                <use xlink:href="{% static 'img/sprite.svg' %}#icon-star_24px"></use>
                            </svg>
                        </div>
                    </div>
                    <a href="{{ second.get_absolute_url }}#show-map" class="m-place-item--button">
                        <p>Детальніше</p>
                        <svg class="icon rightTag">
                            <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                        </svg>
                    </a><a href="{{ second.get_absolute_url }}" class="m-place-item--link"></a>
                    </div>
                    {% empty %}
                        <p>На жаль на сьогодні оновлень немає. Але є на <b><a style="color: #00132b;"
                                                                              href="{% url "places:place_map_seconds" %}">завтра</a></b>
                        </p>
                    {% endfor %}
                    </div>
                </div>
            </div>
    </section>
{% endblock %}
{% block scripts %}
    <script>
        var api_request_postfix = '{% if type == "сток" %}stock{% else %}second{% endif %}/{{ place.id }}';
    </script>
    <script type="text/javascript" src="{% static 'scripts/libs/glide.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/libs/leaflet.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/libs/leaflet-full-screen.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/libs/leaflet-gesture-handling.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/main.js' %}"></script>
{% endblock %}

places/templates/places/place_suggest.html
{% extends 'base.html' %}
{% load static %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="map"{% endblock %}

{% block title %}Запропонувати заклад - Dropmap{% endblock %}

{% block menu-active-item %}ЗАПРОПОНУВАТИ{% endblock %}

{% block map-active %}menu__item--active{% endblock %}

{% block stylesheet %}
{#    for map#}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
{% endblock %}

{% block description %}
    <meta name="description" content="Допоможи нам стати краще і додай секонд або сток. Плюшки у вигляді знижок у магазині включені. Dropmap Drop map.">
{% endblock %}

{% block keywords %}
    <meta name="keywords" content="секонд-хенд, секонд, сток, dropmap, запропонувати">
{% endblock %}
{# END PAGE SETTINGS #}


{% block content %}
    <div class="container">
        <form method="POST" action="">{% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>
{% endblock %}