about/urls.py
from django.urls import path
from about.views import AboutView

app_name = 'about'
urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
]

dropmap/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('', include('places.urls')),
    path('', include('about.urls')),
    path('', include('shop.urls')),
    path('', include('user.urls')),
    path('api/places/', include('places.api.urls')),
    path('api/shop/', include('shop.api.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

places/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'places'
urlpatterns = [
    path('mapseconds/', views.MapSecondsView.as_view(), name='place_map_seconds'),
    path('mapstocks/', views.MapStockView.as_view(), name='place_map_stocks'),
    path('places/second/<int:pk>/', views.SecondDetailView.as_view(), name='second_detail'),
    path('places/stock/<int:pk>/', views.StockDetailView.as_view(), name='stock_detail'),
    # todo change with nothing
    path('places/', views.SecondListView.as_view(), name='place_all'),
    path('places/second/', views.SecondListView.as_view(), name='all_seconds'),
    path('places/stock', views.StockListView.as_view(), name='all_stocks'),
    path('places/suggest/', views.SuggestPlacetView.as_view(), name='place_suggest'),
    ]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('shop/', views.items_list, name='list'),
    path('shop/', views.ListView.as_view(), name='list'),
    path('shop/test', views.send_email, name='email'),
    path('shop/create-item/', views.ItemCreateView.as_view(), name='create'),
    path('shop/<int:pk>/edit', views.ItemUpdateView.as_view(), name='update'),
    path('shop/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('shop/<int:pk>/buy', views.UpdateDelInfoBuy.as_view(), name='buy'),
    path('shop/order/<int:pk>', views.OrderDetail.as_view(), name='order'),
]

user/urls.py
from django.urls import path

from user.forms import UserUpdateDeliveryInfoForm, UserUpdateBuyInfoForm
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/delivery-info/<int:pk>', views.UserDelInfoUpdateView.as_view(form_class=UserUpdateDeliveryInfoForm), name='delivery-info'),
    path('profile/buy-info/<int:pk>', views.UserDelInfoUpdateView.as_view(form_class=UserUpdateBuyInfoForm), name='buy-info'),
    path('profile/my-favourite/', views.UserLikedView.as_view(), name='my-favourite'),
    # path('profile/', views.signup, name='signup'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="uk">
<head>
    <meta charset="utf-8">
    <!-- Global site tag (gtag.js) - Google Analytics-->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-140863969-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-140863969-1');

    </script>
    <!-- -- Facebook Pixel Code-->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '407085826801399');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=407085826801399&amp;ev=PageView&amp;noscript=1"></noscript>
    <!-- End Facebook Pixel Code-->

    <title>{% block title %}DropMap - Unknown{% endblock %}</title>
    {% block description %}
        <meta name="description" content="Dropmap - проект про секонди і стоки у Львові">
    {% endblock %}
    {% block viewport %}
        <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
    {% endblock %}
    {% block keywords %}
        <meta name="keywords" content="секонд-хенд, секонд, графік оновлень">
    {% endblock %}
    <meta name="theme-color" content="#00132B">

    {# FAV ICON OPTIONS #}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest'%}">

    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock %}
</head>
<body data-page={% block data_page %}{% endblock %}>
{% block header %}
    <div class="o-header">
        <nav class="o-header__navbar permanentFill">
            <div class="o-header__container container"><a href="{% url "home:home" %}" class="o-header__href"><img
                    src="{% static 'img/logo.png' %}"
                    alt="logo"
                    class="o-header__logo"></a>
                <div class="menu-mobile-active-item"><a class="menu__item--active">
                    {% block menu-active-item %}{% endblock %}</a>
                </div>
                <div class="m-menu o-header__menu">
                    {#                menu__item--active#}
                    <ul>
                        <li><a href="{% url 'home:home' %}" class="menu__item">ГОЛОВНА</a></li>
                        <li><a href="{% url 'places:place_map_seconds' %}"
                               class="{% block map-active %}{% endblock %} menu__item">КАРТА</a>
                            <svg class="icon downTag">
                                <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                            </svg>
                            <ul>
                                <li><a href="{% url 'places:place_map_seconds' %}" class="sub-menu__item">Секонди |
                                    Оновлення</a></li>
                                <li><a href="{% url 'places:place_map_stocks' %}" class="sub-menu__item">Стоки | Акції</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'places:place_all' %}" class="{% block all-places-active %}{% endblock %} menu__item">УСІ ЗАКЛАДИ</a></li>
                        <li><a href="{% url 'shop:list' %}" class="{% block shop-active %}{% endblock %} menu__item">МАГАЗИН <b>ALPHA</b></a>
                            <svg class="icon downTag">
                                <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                            </svg>
                            <ul>
                                <li><a href="{% url 'shop:create' %}" class="sub-menu__item">Додати товар</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'about:about' %}" class="{% block about-active %}{% endblock %} menu__item">НАПИСАТИ АДМІНУ</a></li>
                        <li><a href="{% url 'user:profile' %}" class="{% block my-profile-active %}{% endblock %} menu__item">
                            {% if user.is_authenticated %}{{ user.get_username|upper }}{% else %}МІЙ
                                ПРОФІЛЬ <b>ALPHA</b>{% endif %}</a>
                            <svg class="icon downTag">
                                <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                            </svg>
                            <ul>
                                <li><a href="./my-stuff" class="sub-menu__item">Мої речі</a></li>
                                <li><a href="./my-favourites" class="sub-menu__item">Мої обрані</a></li>
                                <li><a href="./settings" class="sub-menu__item">Налаштування</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>
                <div class="o-header__hamburger"><a class="hamburger-link">
                    <svg class="icon o-header__hamburger--icon">
                        <use xlink:href="{% static 'img/sprite.svg' %}#icon-burger"></use>
                    </svg>
                </a></div>
            </div>
        </nav>
    </div>
{% endblock %}

{% block content %}
{% endblock %}

<div class="footer">
    <div class="footer--contact container">
        <h3>Зв'язатись з нами</h3>
        <p>У тебе є питання, знайшов помилку або хочеш запропонувати якесь покращення?</p><a
            href="{% url 'about:about' %}"
            class="button-footer">Написати</a>
    </div>
    <div class="footer--socials container">
        <p>Наші контакти</p>
        <div class="social">
            <svg class="icon instagram">
                <use xlink:href="{% static 'img/sprite.svg' %}#icon-inst"></use>
            </svg>
            <a href="https://www.instagram.com/dropmap/" target="_blank" rel="noopener noreferrer">@dropmap</a>
        </div>
        <div class="social">
            <svg class="icon">
                <use xlink:href="{% static 'img/sprite.svg' %}#icon-phone"></use>
            </svg>
            <a href="tel:+380993753939">099 375 39 39</a>
        </div>
    </div>
    <div class="footer--bar">
        <div class="container">
            <p>© 2019 DropMap. All rights reserved.</p>
        </div>
        <div class="footer--bar__button">
            <svg class="icon">
                <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
            </svg>
        </div>
    </div>
</div>
{% block scripts %}
    <script type="text/javascript" src="{% static 'scripts/main.js' %}"></script>
{% endblock %}
</body>
</html>