dropmap/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('', include('places.urls')),
    path('', include('about.urls')),
    path('', include('shop.urls')),
    path('', include('user.urls')),
    path('api/places/', include('places.api.urls')),
    path('api/shop/', include('shop.api.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

shop/api/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import (GetUserFav, UpdateUser, ListUserOrders)

app_name = 'shop-api'
urlpatterns = [
    path('<pk>/add_to_favourite', UpdateUser.as_view(), name='add_to_favourite'),
    path('get_user_favourites', GetUserFav.as_view(), name='get_user_favourites'),
    path('update_user_payment_status', ListUserOrders.as_view(), name='update_user_payment_status'),

]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    # path('shop/', views.items_list, name='list'),
    path('shop/', views.ListView.as_view(), name='list'),
    path('shop/test', views.send_email, name='email'),
    path('shop/create-item/', views.ItemCreateView.as_view(), name='create'),
    path('shop/<int:pk>/edit', views.ItemUpdateView.as_view(), name='update'),
    path('shop/<int:pk>/', views.ItemDetailView.as_view(), name='detail'),
    path('shop/<int:pk>/buy', views.UpdateDelInfoBuy.as_view(), name='buy'),
    path('shop/order/<int:pk>', views.OrderDetail.as_view(), name='order'),
]

shop/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.conf import settings
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill
from django.utils.text import slugify


def upload_location(instance, filename):
    return "shop/%s/%s" % (slugify(instance.name, allow_unicode=True), filename)


ITEM_CONDITION_TYPES = (
    ("SC", "Секонд, є нюанси"),
    ("ST", "Секонд але як нова"),
    ("BN", "Нова річ"),
)

GENDER_TYPES = (
    ("U", "Унісекс"),
    ("M", "Чоловіча"),
    ("F", "Жіноча"),
)

ITEM_SIZES = (
    ("ONE_SIZE", "One size"),
    ("XXS", "XXS"),
    ("XS", "XS"),
    ("S", "S"),
    ("M", "M"),
    ("L", "L"),
    ("XL", "XL"),
    ("XXL", "XXL"),
)

SIZES_CHOICES = [
    ('Одяг', (
        ("XXS", "XXS"),
        ("XS", "XS"),
        ("S", "S"),
        ("M", "M"),
        ("L", "L"),
        ("XL", "XL"),
        ("XXL", "XXL"),
        )
    ),
    ('Взуття', (
            ('41', '41'),
            ('42', '42'),
        )
    ),
    ('ONE_SIZE', 'One size'),
]

STATUSES = (
    ("AVAILABLE", "Продається"),
    ("TO_CHECK", "Чекає підтвердження"),
    ("SOLD", "Продана"),
    # ("BASKET", "В кошику"),
    # ("PAUSED", "Призупинено"),
)

User = settings.AUTH_USER_MODEL


# Create your models here.
class Item(models.Model):
    # todo add category, size + smart filters to it
    name = models.CharField(max_length=50)
    price = models.PositiveSmallIntegerField()
    condition = models.CharField(max_length=4, choices=ITEM_CONDITION_TYPES)
    size = models.CharField(max_length=10, choices=SIZES_CHOICES)
    gender = models.CharField(max_length=3, choices=GENDER_TYPES, default=GENDER_TYPES[0])

    author = models.ForeignKey(User, on_delete=models.CASCADE)

    description = models.CharField(max_length=256, blank=True, null=True)
    condition_notes = models.CharField(max_length=256, blank=True, null=True)
    measurements = models.CharField(max_length=256, blank=True, null=True)
    status = models.CharField(max_length=9, choices=STATUSES, default=STATUSES[0])

    was_suggested = models.BooleanField(default=False,
                                        help_text="показує чи взагалі цю річ додали через адмінку або через форму")
    promoting = models.BooleanField(default=False, help_text="Просування речі. Викидує її на перші сторінки")
    on_site = models.BooleanField(default=True,
                                  help_text='Глобальна настройка. Просто забирає річ з списків якщо вимкнена')
    created = models.DateTimeField(auto_now_add=True)

    # todo main {list square 170x170 , slider 390x390 , full quality bit lower}. others {slider , full}
    # main image original & cropping


    main_image = ProcessedImageField(upload_to=upload_location,
                                     format='JPEG',
                                     options={'quality': 80}, verbose_name="Головне фото")

    # slider_image = ImageSpecField(source='main_image',
    #                               processors=[ResizeToFill(390, 390)],
    #                               format='JPEG',
    #                               options={'quality': 80})
    # additional images
    image2 = ProcessedImageField(upload_to=upload_location,
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)
    # slider_image2 = ProcessedImageField(upload_to=upload_location,
    #                                     processors=[ResizeToFill(390, 390)],
    #                                     format='JPEG',
    #                                     options={'quality': 80}, blank=True, null=True)
    image3 = ProcessedImageField(upload_to=upload_location,
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)
    # slider_image3 = ProcessedImageField(upload_to=upload_location,
    #                                     processors=[ResizeToFill(390, 390)],
    #                                     format='JPEG',
    #                                     options={'quality': 80}, blank=True, null=True)
    image4 = ProcessedImageField(upload_to=upload_location,
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)
    # slider_image4 = ProcessedImageField(upload_to=upload_location,
    #                                     processors=[ResizeToFill(390, 390)],
    #                                     format='JPEG',
    #                                     options={'quality': 80}, blank=True, null=True)
    image5 = ProcessedImageField(upload_to=upload_location,
                                 format='JPEG',
                                 options={'quality': 80}, blank=True, null=True)

    # slider_image5 = ProcessedImageField(upload_to=upload_location,
    #                                     processors=[ResizeToFill(390, 390)],
    #                                     format='JPEG',
    #                                     options={'quality': 80}, blank=True, null=True)

    def image2_exist(self):
        return True if self.image2 else None

    def image3_exist(self):
        return True if self.image2 else None

    def image4_exist(self):
        return True if self.image2 else None

    def image5_exist(self):
        return True if self.image2 else None

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail', kwargs={'pk': self.id})

    # def save(self, *args, **kwargs):
    #     super(Item, self).save(*args, **kwargs)


PAYMENT_STATUSES = (
    ("TO_PAY", "Чекає оплати"),
    ("NOT_ENOUGH", "Не достатньо оплачено"),
    ("PAID", "Оплачено"),
)
SHIPPING_TYPES = (
    (0, "Самовивіз + 0 грн"),
    (20, "УКР Поштою по місту/області + 20 грн"),
    (27, "УКР Поштою по Україні + 27 грн"),
    (45, "Новою поштому по місту + 45 грн"),
    (50, "Новою поштому по місту + 50 грн"),
    (55, "Новою Поштою по Україні + 55 грн"),
)


class Order(models.Model):
    item = models.ForeignKey(Item, null=True, on_delete=models.SET_NULL)
    payment_status = models.CharField(max_length=9, default=PAYMENT_STATUSES[0], choices=PAYMENT_STATUSES)
    client = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    shipping_type = models.IntegerField(choices=SHIPPING_TYPES)
    total_cost = models.IntegerField()
    snippet = models.TextField(max_length=256, verbose_name="Примітки для продавця", blank=True, null=True)
    viewed = models.BooleanField(default=False)
    # info which is filling on pay check
    paid_by = models.CharField(max_length=100, blank=True, null=True)
    pay_comment = models.CharField(max_length=256, blank=True, null=True)
    pay_amount = models.CharField(max_length=256, blank=True, null=True)
    not_enough = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('shop:order', kwargs={'pk': self.id})

    def __str__(self):
        return self.item.name if self.item.name else 'Item was deleted'

shop/forms.py
from django import forms

from django.contrib.auth import get_user_model
from django.forms import ModelForm

from shop.models import SHIPPING_TYPES

User = get_user_model()



class UserUpdateDeliveryBuyForm(ModelForm):
    shipping_type = forms.ChoiceField(choices=SHIPPING_TYPES)
    snippet = forms.CharField(max_length=256, label="Примітки для продавця", required=False)

    class Meta:
        model = User
        # Custom fields
        fields = ['shipping_type','pib', 'city', 'address', 'email', 'phone', 'snippet']

shop/api/views.py
import re
from datetime import datetime, timedelta
from django.contrib.auth import get_user_model
from django.http import Http404
from rest_framework import permissions, status
from rest_framework.generics import UpdateAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from shop.api.serializers import UserSerializer, OrderSerializer
from shop.models import Item, Order
from hashlib import sha1, md5
from requests import post

User = get_user_model()


class GetUserFav(APIView):

    def get(self, request, format=None):
        user = User.objects.get(username=self.request.user)
        serializer = UserSerializer(user)
        return Response(serializer.data)


class UpdateUser(APIView):
    def put(self, request, pk, format=None):
        user = User.objects.get(username=self.request.user)
        # snippet = self.get_object(pk)
        serializer = UserSerializer(user, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ListUserOrders(APIView):
    """
    View to update statuses of orders and return results
    """

    # authentication_classes = [authentication.TokenAuthentication]
    # permission_classes = [permissions.IsAdminUser]

    def get(self, request, format=None):
        queryset = Order.objects.all()
        # todo fix logic in future. it's silly to return all the
        # todo get last payments here and update values

        url = "https://api.privatbank.ua/p24api/rest_fiz"
        password = "L8Lp1g9w35ycGWAktvy18IE4WOvQ33Uu"
        head = """<?xml version="1.0" encoding="UTF-8"?>
        <request version="1.0">
            <merchant>
                <id>148717</id>
                <signature>"""
        end_head = """</signature>
            </merchant>
            <data>
                """
        data = """<oper>cmt</oper>
                            <wait>0</wait>
                            <test>0</test>
                            <payment id="">
                                <prop name="sd" value="{:%d.%m.%Y}" />
                                <prop name="ed" value="{:%d.%m.%Y}" />
                                <prop name="card" value="5168755436867846" />
                            </payment>""".format(datetime.today() - timedelta(days=2), datetime.today())

        footer = """
            </data>
        </request>"""

        signature_md5 = md5((data + password).encode('utf-8')).hexdigest()
        signature_done = sha1(signature_md5.encode('utf-8')).hexdigest()

        data_done = head + signature_done + end_head + data + footer

        res = post(url, data=data_done, headers={'Content-Type': 'application/xml; charset=UTF-8'})
        # https://regex101.com/r/6Ga089/3 url for reg exp

        # just for testing
        # text = '<?xml version="1.0" encoding="UTF-8"?><response version="1.0"><merchant><id>148717</id><signature>ada4d659f205ab66600d586039da1415ed1e05bb</signature></merchant><data><oper>cmt</oper><info><statements status="excellent" credit="401.0" debet="872.52"><statement card="5168755436867846" appcode="301017" trandate="2019-09-05" trantime="22:39:00" amount="1.00 UAH" cardamount="1.00 UAH" rest="346.61 UAH" terminal="PrivatBank, CS980400" description="Перевод с карты ПриватБанка через приложение Приват24. Отправитель: Сухарева Катерина Костянтинівна. Комментарий к платежу: заказ 123 курлык."/><statement card="5168755436867846" appcode="737025" trandate="2019-08-30" trantime="13:59:00" amount="104.50 UAH" cardamount="-110.00 UAH" rest="345.61 UAH" terminal="Vintage, L1IF2MPT" description="Одежда: Second Hand Vintage, Iвано-Франкiвськ, Коновальца, 100"/><statement card="5168755436867846" appcode="366016" trandate="2019-08-20" trantime="16:14:00" amount="200.00 UAH" cardamount="200.00 UAH" rest="455.61 UAH" terminal="PrivatBank, CS980400" description="Перевод с карты ПриватБанка через приложение Приват24. Отправитель: Паршуков Іван Олександрович"/><statement card="5168755436867846" appcode="255015" trandate="2019-08-20" trantime="15:58:00" amount="200.00 UAH" cardamount="200.00 UAH" rest="255.61 UAH" terminal="PrivatBank, CS980400" description="Перевод с карты ПриватБанка через Приват24. Отправитель: Товт Василь Васильович"/><statement card="5168755436867846" appcode="96202Z" trandate="2019-08-18" trantime="12:41:00" amount="257.52 UAH" cardamount="-257.52 UAH" rest="55.61 UAH" terminal="GIPERMARKET EPICENTR, 20340222" description="Ремонт/Строительство: GIPERMARKET EPICENTR, Ivano-Frankiv"/><statement card="5168755436867846" appcode="532023" trandate="2019-08-11" trantime="17:36:00" amount="505.00 UAH" cardamount="-505.00 UAH" rest="313.13 UAH" terminal="P24 DB M UA, I0110SWA" description="Перевод со своей карты"/></statements></info></data></response>'

        text = '\n<statement card="5168755436867846" appcode="301017" trandate="2019-09-05" trantime="22:39:00" amount="999999999.00 UAH" cardamount="1.00 UAH" rest="346.61 UAH" terminal="PrivatBank, CS980400" description="Перевод с карты ПриватБанка через приложение Приват24. Отправитель: alex zako. Комментарий к платежу: заказ 13."/>'
        # todo change to res.text in matches
        matches = re.findall(
            '^<statement.+?amount="([0-9]+\.[0-9]+) UAH".+?Отправитель: (.+?). Комментарий к платежу: (.*?(\d+).*?)."\/>$',
            text, re.M)

        if matches:
            for match in matches:

                # o = queryset.filter(item__price__gte=float(match[0])).filter(id=int(match[3])).first()
                try:
                    # the logic is someone else may pay order
                    o = Order.objects.get(payment_status="TO_PAY", id=int(match[3]))
                except Order.DoesNotExist:
                    o = None

                if o:
                    if float(o.total_cost) > float(match[0]):
                        o.payment_status = "NOT_ENOUGH"
                        # todo notify me if someone pays not enough
                    else:
                        o.payment_status = "PAID"

                    o.paid_by = match[1]
                    o.pay_comment = match[2]
                    o.pay_amount = float(match[0])
                    o.save()
                    # todo sent email to author here. That item was sold

        serializer = OrderSerializer(queryset, many=True)
        return Response(serializer.data)

shop/templates/shop/item_buy.html
{% extends 'base.html' %}
{% load static %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="shop-update"{% endblock %}

{% block title %}Купити - Dropmap{% endblock %}

{% block menu-active-item %}КУПИТИ{% endblock %}

{% block shop-active %}menu__item--active{% endblock %}

{# END PAGE SETTINGS #}

{% block content %}
    <div class="container">
        <form method="POST" action="">{% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Submit">

        </form>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    <a href="">CONTINUE</a>
    </div>
{% endblock %}

shop/templates/shop/item_suggest.html
{% extends 'base.html' %}
{% load static %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="shop-create"{% endblock %}

{% block title%}Створити оголошення - Dropmap{% endblock %}

{% block menu-active-item %}СТВОРИТИ{% endblock %}

{% block shop-active %}menu__item--active{% endblock %}

{# END PAGE SETTINGS #}

{% block content %}
    <div class="container">
<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" value="Submit">

</form>
    </div>
{% endblock %}

shop/templates/shop/item_update.html
{% extends 'base.html' %}
{% load static %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="shop-update"{% endblock %}

{% block title %}Редагувати річ - Dropmap{% endblock %}

{% block menu-active-item %}РЕДАГУВАТИ{% endblock %}

{% block shop-active %}menu__item--active{% endblock %}

{# END PAGE SETTINGS #}

{% block content %}
    <div class="container">
        <form method="POST" action="">{% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <input type="submit" value="Submit">

        </form>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

shop/templates/shop/list_item.html
{% extends 'base.html' %}
{% load static %}
{% load app_filters %}
{% load thumbnail %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="shop-create"{% endblock %}

{% block title %}Магазин - Dropmap{% endblock %}

{% block menu-active-item %}МАГАЗИН{% endblock %}

{% block shop-active %}menu__item--active{% endblock %}

{% block description %}
    <meta name="description" content="Інтернет магазин Dropmap. Речі які точно будуть дешевші ніж у звичайних магазинах. Drop map">
{% endblock %}

{% block keywords %}
    <meta name="keywords" content="секонд-хенд, речі, секонд, сток, dropmap, львів">
{% endblock %}

{# END PAGE SETTINGS #}

{% block content %}
    <!-- fix if one-->
    <div class="breadcrumb">
        <ul class="breadcrumb__list">
            <li class="breadcrumb__item">
                <!-- if breadcrumb is single--><a href="#" title="DROPMAP.COM.UA" class="breadcrumb__link">DROPMAP.COM.UA</a>
            </li>
            <li class="breadcrumb__item"><span class="breadcrumb__link-current">МАГАЗИН</span></li>
        </ul>
    </div>
    <form method="get">
        {% for field in filter.form %}
            <div style="font-weight: bold;
                    margin:4px 0 ; {% if field.errors %}color: #c41200{% endif %};
                    font-size: 14px;">
                {{ field.name }} <br>
            </div>

            {{ field.help_text }}
            {{ field }}
        {% endfor %}



        <button type="submit">Search</button>
    </form>
{#    <div class="container"><a href="{% url "shop:create" %}" style="background-color: #00132B;"#}
{#                              class="button-fullcolor button-fullcolor-shop">Додати товар</a>#}
{#    </div>#}

{#    <section class="o-shop-topbar">#}
{#        <div class="container">#}
{#            <div class="m-shop-topbar">#}
{#                <div class="filter-button">#}
{#                    <svg class="icon filter">#}
{#                        <use xlink:href="../img/sprite.svg#icon-filter"></use>#}
{#                    </svg>#}
{#                    <p>Фільтр і сортування</p>#}
{#                    <svg class="icon arrow">#}
{#                        <use xlink:href="../img/sprite.svg#icon-arrow"></use>#}
{#                    </svg>#}
{#                </div>#}
{#                <div class="drop-down-filter-bar">#}
{#                    <form method="get">#}
{#                        {% for field in filter.form %}#}
{#                            <div style="font-weight: bold;#}
{#                                    margin:4px 0 ; {% if field.errors %}color: #c41200{% endif %};#}
{#                                    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 14px;">#}
{#                                {{ field.name }} <br>#}
{#                            </div>#}
{##}
{#                            {{ field.help_text }}#}
{#                            {{ field }}#}
{#                        {% endfor %}#}
{##}
{##}
{##}
{#                        <button type="submit">Search</button>#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
    <section class="o-shop">
        <div class="container">
            <ul class="o-shop__items-holder shop-offer-item-black">
                {% for item in item_list %}
                    <li class="product-item">
                        <article class="shop-offer-item">
                            <div class="image-container">
                                <a href="{{ item.get_absolute_url }}"
                                   title="{{ item.name|capfirst }}"
                                   class="item-link">
                                    {% thumbnail item.main_image "170x170" crop="center" as im %}
                                        <img src="{{ im.url }}"
                                             alt="{{ item.name|capfirst }} - Dropmap" class="item-image">
                                    {% endthumbnail %}
                                </a>
                            </div>
                            {% if item.condition == "BN" %}
                                <div style="background-color:#009748;" class="shop-offer-item--label">
                                <span>Нова річ</span>
                            {% elif item.condition == "ST" %}
                                <div style="background-color:#CF7D35;" class="shop-offer-item--label">
                                <span>Секонд як нова</span>
                            {% else %}
                                <div style="background-color:#CE0030;" class="shop-offer-item--label">
                                <span>Секонд, є нюанси</span>
                            {% endif %}
                            </div>
                            <div class="item-details">
                                <h3 class="item-heading"><a href="{{ item.get_absolute_url }}"
                                                            title="{{ item.name|capfirst }}">{{ item.name|capfirst }}</a>
                                </h3>
                                <strong
                                        class="item-price"><span
                                        class="price-regular">{{ item.price }} грн</span></strong>
                                <div class="item-size-brand"><span>Розмір - {{ item.get_size_display }}</span>
                                </div>
                            </div>
                        </article>
                    </li>
                {% endfor %}

            </ul>


            {% if is_paginated %}
                <div class="o-allplaces--paginator">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.get_full_path|fix_url }}page={{ page_obj.previous_page_number }}"
                           class="button-paginator backward">
                    {% else %}
                        <a href="#" class="button-paginator backward disable">
                    {% endif %}
                    <div class="text">Сюда</div>
                    <div class="button-paginator--holder">
                        <svg class="icon icon-white small">
                            <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                        </svg>
                    </div>
                    </a>

                    <span>Сторінка {{ page_obj.number }} з {{ paginator.num_pages }}. </span>

                    {% if page_obj.has_next %}
                        <a href="{{ request.get_full_path|fix_url }}page={{ page_obj.next_page_number }}"
                           class="button-paginator forward">
                    {% else %}
                        <a href="#" class="button-paginator forward disable">
                    {% endif %}
                    <div class="text">Туда</div>
                    <div class="button-paginator--holder">
                        <svg class="icon icon-white small">
                            <use xlink:href="{% static 'img/sprite.svg' %}#icon-arrow"></use>
                        </svg>
                    </div>
                    </a>
                </div>
            {% endif %}


        </div>
    </section>
{% endblock %}

shop/templates/shop/order_detail.html
{% extends 'base.html' %}
{% load static %}

{# PAGE SETTINGS #}

{% block data_page %}data-page="shop-update"{% endblock %}

{% block title %}Замовлення {{ order.id }} - Dropmap{% endblock %}

{% block menu-active-item %}КУПИТИ{% endblock %}

{% block shop-active %}menu__item--active{% endblock %}

{# END PAGE SETTINGS #}

{% block content %}
    <div class="container">
        <h1>замовлення номер {{ order.id }} - {{ order.item }}</h1>
        <h4>
            Ми надіслали тобі чек і інформацію куди оплачувати. У тебе є 2 години для оплати</h4>
        <p>Статус оплати {{ order.get_payment_status_display }}</p>
        <p>Бот автоматично перевірить оплату втою оплату на протязі години. Якщо хочеш швидче то написни на кнопку</p>

        <a href="#">Я оплатив. Перевірити оплату</a>
        <a href="#">Я оплатив. А воно щось не підтверджує</a>
    </div>
{% endblock %}